# image: node:8

# Environment variables needed:
#
# API_BASE_URL: the base URL of the manuscripts-api endpoint
# NOW_TOKEN: the token for authentication with the now.sh API
# NOW_TEAM: the now.sh team name
# SERVE_USER: the user for HTTP authentication
# SERVE_PASSWORD: the password for HTTP authentication

# https://gitlab.com/gitlab-org/gitlab-runner/issues/2495
variables:
  NOW_APP: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
  NOW_DOMAIN: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.now.sh

#before_script:
#  - if [ -x "$(command -v nvm)" ]; then nvm use v8.9; fi

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - yarn install --frozen-lockfile --non-interactive
    - yarn lint
    - yarn test
  tags:
    - nodejs-8

build:
  stage: build
  script:
    - yarn install --frozen-lockfile --non-interactive --production
    - cp .env.example .env
    - API_BASE_URL=$API_BASE_URL yarn build
  artifacts:
    expire_in: 1 hour
    paths:
      - dist
  tags:
    - nodejs-8

.review/start:
  stage: deploy
  dependencies:
    - build
  script:
    - yarn install --frozen-lockfile --non-interactive --production
    - cp deploy.json dist/package.json
    - NOW_DEPLOY_URL=$(yarn run --silent now --token $NOW_TOKEN --team $NOW_TEAM --name $NOW_APP --env SERVE_USER=$SERVE_USER --env SERVE_PASSWORD=$SERVE_PASSWORD --public dist)
    - yarn run --silent now --token $NOW_TOKEN --team $NOW_TEAM alias set "$NOW_DEPLOY_URL" "$NOW_DOMAIN"
    - yarn run --silent now --token $NOW_TOKEN --team $NOW_TEAM rm --safe "$NOW_DOMAIN"
  allow_failure: true
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$SERVE_USER:$SERVE_PASSWORD@$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.now.sh
    on_stop: review/stop
  only:
    - branches
  except:
    - master
  tags:
    - nodejs-8

.review/stop:
  stage: deploy
  dependencies: []
  script:
    - yarn install --frozen-lockfile --non-interactive --production
    - yarn run --silent now rm --token $NOW_TOKEN --team $NOW_TEAM --yes $NOW_APP
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - branches
  except:
    - master
  tags:
    - nodejs-8

.pages:
  stage: deploy
  dependencies:
    - build
  script:
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - nodejs-8
