# image: node:8

# Environment variables needed:
#
# API_BASE_URL: the base URL of the manuscripts-api endpoint
# NOW_TOKEN: the token for authentication with the now.sh API
# NOW_TEAM: the now.sh team name
# SERVE_USER: the user for HTTP authentication
# SERVE_PASSWORD: the password for HTTP authentication

# https://gitlab.com/gitlab-org/gitlab-runner/issues/2495
variables:
  NOW_APP: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
  NOW_DOMAIN: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.now.sh

#before_script:
#  - if [ -x "$(command -v nvm)" ]; then nvm use v8.9; fi

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - yarn install --frozen-lockfile --non-interactive
    - yarn lint
    - yarn test
  tags:
    - nodejs-8

build:
  stage: build
  script:
    - yarn install --frozen-lockfile --non-interactive --production
    - cp .env.example .env
    - API_BASE_URL=$API_BASE_URL yarn build
  artifacts:
    expire_in: 1 hour
    paths:
      - dist
  tags:
    - nodejs-8

deploy_production:
  stage: deploy
  dependencies:
    - build
  script:
    - ./bin/deploy-production.sh
  tags:
    - nodejs-8
    - awscli
  only:
    - /\d\..*$/ # tags which are prefixed with a digit + ., i.e. version numbers like 1.2.3
    - triggers
  
deploy_dev:
  stage: deploy
  dependencies:
    - build
  script:
    - ./bin/deploy-dev.sh
  tags:
    - nodejs-8
    - awscli
  only:
    - master
    - triggers
  