image: registry.gitlab.com/mpapp-private/manuscripts-frontend/node8-aws

# Environment variables needed:
#
# API_BASE_URL: the base URL of the manuscripts-api endpoint
# API_APPLICATION_ID: the application ID sent to the manuscripts-api endpoint
# SYNC_GATEWAY_URL: the base URL of the sync gateway endpoint
# S3_BUCKET: S3 bucket name
# CLOUDFRONT_ID: CloudFront distribution ID
# STORYBOOK_BUCKET_NAME: Storybook S3 bucket name
# STORYBOOK_DISTRIBUTION_ID: Storybook CloudFront distribution ID

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - yarn install --frozen-lockfile --non-interactive
    - yarn lint
    - yarn test --coverage
    - yarn build
  tags:
    - nodejs-8

storybook:
  environment:
    name: storybook
    url: https://storybook.manuscripts.io/
  stage: deploy
  script: scripts/deploy-storybook.sh
  tags:
    - nodejs-8
    - awscli
  only:
    - master
    - triggers

storybook_manual:
  environment:
    name: storybook
    url: https://storybook.manuscripts.io/
  stage: deploy
  script: scripts/deploy-storybook.sh
  tags:
    - nodejs-8
    - awscli
  when: manual

deploy_production:
  environment:
    name: production
    url: https://www.manuscripts.io/
  stage: deploy
  script: scripts/deploy.sh
  tags:
    - nodejs-8
    - awscli
  only:
    - /^v\d+\./ # only deploy release tags, which start with "v" and a version number

deploy_dev:
  environment:
    name: dev
    url: https://dev.manuscripts.io/
  stage: deploy
  script: scripts/deploy.sh
  tags:
    - nodejs-8
    - awscli
  only:
    refs:
      - master
      - triggers
    variables:
      - $CI_COMMIT_MESSAGE =~ /#deploy-dev/

deploy_dev_manual:
  environment:
    name: dev
    url: https://dev.manuscripts.io/
  stage: deploy
  script: scripts/deploy.sh
  tags:
    - nodejs-8
    - awscli
  when: manual

publish_image:
  stage: deploy
  environment:
    name: docker
  variables:
    CONTAINER_IMAGE: registry.gitlab.com/mpapp-private/manuscripts-frontend/manuscripts-frontend:latest
  script: scripts/publish-image.sh
  tags:
    - docker-ce
  only:
    - master


