# Environment variables needed:
#
# API_BASE_URL: the base URL of the manuscripts-api endpoint
# API_APPLICATION_ID: the application ID sent to the manuscripts-api endpoint
# SYNC_GATEWAY_URL: the base URL of the sync gateway endpoint
# S3_BUCKET: S3 bucket name
# CLOUDFRONT_ID: CloudFront distribution ID
# STORYBOOK_BUCKET_NAME: Storybook S3 bucket name
# STORYBOOK_DISTRIBUTION_ID: Storybook CloudFront distribution ID

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - yarn install --frozen-lockfile --non-interactive
    - yarn lint
    - yarn test
  tags:
    - nodejs-8

build:
  stage: build
  script:
    - yarn install --frozen-lockfile --non-interactive --production
    - yarn build
  artifacts:
    expire_in: 1 hour
    paths:
      - dist
  tags:
    - nodejs-8

storybook:
  environment:
    name: storybook
    url: https://storybook.manuscripts.io/
  stage: deploy
  script:
    - yarn install --frozen-lockfile --non-interactive
    - yarn run build-storybook
    - aws s3 sync --include "*" --cache-control "max-age=2592000" --acl "public-read" --sse "AES256" storybook-static/ "s3://${STORYBOOK_BUCKET_NAME}"
    - aws cloudfront create-invalidation --distribution-id ${STORYBOOK_DISTRIBUTION_ID} --paths /index.html /
  tags:
    - nodejs-8
    - awscli
  only:
    - master
    - triggers
    - manual

deploy_production:
  environment:
    name: production
    url: https://www.manuscripts.io/
  stage: deploy
  dependencies:
    - build
  script:
    - aws s3 cp --recursive --include "*" --cache-control "max-age=2592000" --acl "public-read" --sse "AES256" dist/ s3://${S3_BUCKET}
    - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths /index.html /
  tags:
    - nodejs-8
    - awscli
  only:
    - /^v\d+\./ # only deploy release tags, which start with "v" and a version number

deploy_dev:
  environment:
    name: dev
    url: https://dev.manuscripts.io/
  stage: deploy
  dependencies:
    - build
  script:
    - aws s3 cp --recursive --include "*" --cache-control "max-age=2592000" --acl "public-read" --sse "AES256" dist/ s3://${S3_BUCKET}
    - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths /index.html /
  tags:
    - nodejs-8
    - awscli
  only:
    - master
    - triggers
    - manual
