image: registry.gitlab.com/mpapp-private/manuscripts-frontend/node8-aws

# Environment variables needed:
#
# API_BASE_URL: the base URL of the manuscripts-api endpoint
# API_APPLICATION_ID: the application ID sent to the manuscripts-api endpoint
# DISCOURSE_HOST: the base URL of the Discourse host
# SYNC_GATEWAY_URL: the base URL of the sync gateway endpoint
# S3_BUCKET: S3 bucket name
# CLOUDFRONT_ID: CloudFront distribution ID
# STORYBOOK_BUCKET_NAME: Storybook S3 bucket name
# STORYBOOK_DISTRIBUTION_ID: Storybook CloudFront distribution ID

before_script:
  - . scripts/export-variables.sh
  - npm config set //atypon-npm-registry.herokuapp.com/:_authToken ${NPM_TOKEN}

stages:
  - test

lint_test_build:
  stage: test
  script:
    - yarn install --frozen-lockfile --non-interactive
    - yarn typecheck
    - yarn lint
    - yarn test --coverage
    - yarn build
  tags:
    - nodejs-8
  artifacts:
    paths:
      - ./coverage
    expire_in: 1 week
    when: always
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

.testcafe-chromium:
  stage: test
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com
    - ./testcafe/scripts/run-tests.sh testcafe_chromium
  after_script:
    - yarn run docker-compose:testcafe down -v
  artifacts:
    paths:
      - ./screenshots
    expire_in: 1 week
    when: on_failure
  tags:
    - docker-compose
  only:
    - master
    - triggers

.testcafe-firefox:
  stage: test
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com
    - ./testcafe/scripts/run-tests.sh testcafe_firefox
  after_script:
    - yarn run docker-compose:testcafe down -v
  artifacts:
    paths:
      - ./screenshots
    expire_in: 1 week
    when: on_failure
  tags:
    - docker-compose
  only:
    - master
    - triggers

testcafe-firefox-manual:
  stage: test
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com
    - ./testcafe/scripts/run-tests.sh testcafe_firefox
  after_script:
    - yarn run docker-compose:testcafe down -v
  artifacts:
    paths:
      - ./screenshots
    expire_in: 1 week
    when: on_failure
  when: manual
  tags:
    - docker-compose

testcafe-chromium-manual:
  stage: test
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com
    - ./testcafe/scripts/run-tests.sh testcafe_chromium
  after_script:
    - yarn run docker-compose:testcafe down -v
  artifacts:
    paths:
      - ./screenshots
    expire_in: 1 week
    when: on_failure
  when: manual
  tags:
    - docker-compose
