image: node:8

# TODO: env

stages:
  - lint
  - test
  - build
  - deploy

before_script:
  - yarn

cache:
  paths:
    - node_modules/

lint:
  stage: lint
  script: yarn lint

test:
  stage: test
  script: yarn test

build:
  stage: build
  script:
    - cp .env.example .env
    - yarn build
  artifacts:
    paths:
      - dist/

.pages:
  stage: deploy
  script:
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master

.deploy_review:
  stage: deploy
  script:
    - echo "Deploy a review app"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master
