image: node:12-buster

# Environment variables needed:
#
# API_BASE_URL: the base URL of the manuscripts-api endpoint
# API_APPLICATION_ID: the application ID sent to the manuscripts-api endpoint
# DISCOURSE_HOST: the base URL of the Discourse host
# SYNC_GATEWAY_URL: the base URL of the sync gateway endpoint
# S3_BUCKET: S3 bucket name
# CLOUDFRONT_ID: CloudFront distribution ID
# STORYBOOK_BUCKET_NAME: Storybook S3 bucket name
# STORYBOOK_DISTRIBUTION_ID: Storybook CloudFront distribution ID

before_script:
  - . scripts/export-variables.sh

stages:
  - test
#  - pages

lint_test_build:
  stage: test
  script:
    - yarn install --frozen-lockfile --non-interactive
    - yarn typecheck
    - yarn lint
    - yarn test --ci --coverage --reporters=default --reporters=jest-junit
    - ALLOW_MISSING_VARIABLES=1 yarn build
    - yarn bundlesize
  coverage: '/Statements\s*:\s*(\d+\.\d+)%/'
  artifacts:
    reports:
      junit: junit.xml

.integration_tests:
  stage: test
  script:
    - yarn install --frozen-lockfile --non-interactive
    - yarn test:integration

#pages:
#  stage: pages
#  script:
#    - yarn install --frozen-lockfile --non-interactive
#    - mkdir public
#    - cp LICENSE public/
#    - cp node_modules/@manuscripts/assets/png/CPALLicenseSplash.png public/
#  artifacts:
#    paths:
#      - public
#  only:
#    refs:
#      - master
