const nodeTypes: Map<string, string> = new Map([
  ['affiliation', 'MPAffiliation'],
  ['bibliographic_date', 'MPBibliographicDate'],
  ['bibliographic_name', 'MPBibliographicName'],
  ['bibliography', 'MPBibliographyElement'],
  ['bibliography_item', 'MPBibliographyItem'],
  ['bibliography_section', 'MPSection'],
  ['citation_item', 'MPCitationItem'],
  ['citation', 'MPCitation'],
  ['code_block', 'MPListingElement'],
  ['contributor', 'MPContributor'],
  ['cross_reference', 'MPAuxiliaryObjectReference'],
  ['equation_block', 'MPEquationElement'],
  ['figure', 'MPFigureElement'],
  ['figure_image', 'MPFigure'],
  ['keyword', 'MPKeyword'],
  ['bullet_list', 'MPListElement'],
  ['ordered_list', 'MPListElement'],
  ['manuscript', 'MPManuscript'],
  ['paragraph', 'MPParagraphElement'],
  ['project', 'MPProject'],
  ['section', 'MPSection'],
  ['table', 'MPTable'],
  ['table_figure', 'MPTableElement'],
])

export default nodeTypes
