export const nodeNames: Map<string, string> = new Map([
  ['bibliography', 'Bibliography'],
  ['bibliography_item', 'Bibliography Item'],
  ['bibliography_section', 'Section'],
  ['citation_item', 'Citation Item'],
  ['citation', 'Citation'],
  ['code_block', 'Listing'],
  ['cross_reference', 'Cross Reference'],
  ['equation_block', 'Equation'],
  ['figure', 'Figure'],
  ['figure_image', 'Figure'],
  ['bullet_list', 'Bullet List'],
  ['ordered_list', 'Ordered List'],
  ['manuscript', 'Manuscript'],
  ['paragraph', 'Paragraph'],
  ['section', 'Section'],
  ['table', 'Table'],
  ['table_figure', 'Table'],
])
