version: '3'

services:
  client:
    build:
      context: ../../..
      dockerfile: docker/client/production/Dockerfile
    environment:
      - API_BASE_URL
      - API_APPLICATION_ID
      - CSL_DATA_URL
      - GIT_VERSION
      - GIT_COMMIT_HASH
      - SENTRY_PUBLIC_DSN
      - SYNC_GATEWAY_URL
      - WAYF_URL
      - WAYF_KEY
    ports:
      - 8080:80
    volumes:
      - yarn-cache:/cache/yarn

volumes:
  yarn-cache:
  # external: true

