version: '3'

services:
  client:
    build:
      context: ../../..
      dockerfile: docker/client/development/Dockerfile
    env_file:
      - .env
    environment:
      - GIT_VERSION
      - GIT_COMMIT_HASH
    ports:
      - 8080:8080
    volumes:
      - yarn-cache:/cache/yarn

volumes:
  yarn-cache:
  # external: true

