/*!
 * The contents of this file are subject to the Common Public Attribution License Version 1.0 (the “License”); you may not use this file except in compliance with the License. You may obtain a copy of the License at https://mpapp-public.gitlab.io/manuscripts-frontend/LICENSE. The License is based on the Mozilla Public License Version 1.1 but Sections 14 and 15 have been added to cover use of software over a computer network and provide for limited attribution for the Original Developer. In addition, Exhibit A has been modified to be consistent with Exhibit B.
 *
 * Software distributed under the License is distributed on an “AS IS” basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language governing rights and limitations under the License.
 *
 * The Original Code is manuscripts-frontend.
 *
 * The Original Developer is the Initial Developer. The Initial Developer of the Original Code is Atypon Systems LLC.
 *
 * All portions of the code written by Atypon Systems LLC are Copyright (c) 2019 Atypon Systems LLC. All Rights Reserved.
 */

import { ResearchField } from '../../types/templates'

export const researchFields: ResearchField[] = [
  {
    _id: 'MPResearchField:anthropology',
    objectType: 'MPResearchField',
    name: 'Anthropology',
    priority: 100,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:astronomy',
    objectType: 'MPResearchField',
    name: 'Astronomy',
    priority: 150,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:biology',
    objectType: 'MPResearchField',
    name: 'Biology',
    priority: 200,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:botany',
    objectType: 'MPResearchField',
    name: 'Botany',
    priority: 250,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:science',
    objectType: 'MPResearchField',
    name: 'Science',
    priority: 300,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:zoology',
    objectType: 'MPResearchField',
    name: 'Zoology',
    priority: 350,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:geography',
    objectType: 'MPResearchField',
    name: 'Geography',
    priority: 400,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:chemistry',
    objectType: 'MPResearchField',
    name: 'Chemistry',
    priority: 450,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:engineering',
    objectType: 'MPResearchField',
    name: 'Engineering',
    priority: 500,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:generic-base',
    objectType: 'MPResearchField',
    name: 'Generic base',
    priority: 550,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:geology',
    objectType: 'MPResearchField',
    name: 'Geology',
    priority: 600,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:medicine',
    objectType: 'MPResearchField',
    name: 'Medicine',
    priority: 650,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:physics',
    objectType: 'MPResearchField',
    name: 'Physics',
    priority: 700,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:communications',
    objectType: 'MPResearchField',
    name: 'Communications',
    priority: 750,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:linguistics',
    objectType: 'MPResearchField',
    name: 'Linguistics',
    priority: 800,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:political_science',
    objectType: 'MPResearchField',
    name: 'Political science',
    priority: 850,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:social_science',
    objectType: 'MPResearchField',
    name: 'Social science',
    priority: 900,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:philosophy',
    objectType: 'MPResearchField',
    name: 'Philosophy',
    priority: 950,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:psychology',
    objectType: 'MPResearchField',
    name: 'Psychology',
    priority: 975,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:theology',
    objectType: 'MPResearchField',
    name: 'Theology',
    priority: 1000,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:math',
    objectType: 'MPResearchField',
    name: 'Math',
    priority: 1050,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:sociology',
    objectType: 'MPResearchField',
    name: 'Sociology',
    priority: 1100,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:history',
    objectType: 'MPResearchField',
    name: 'History',
    priority: 1200,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:humanities',
    objectType: 'MPResearchField',
    name: 'Humanities',
    priority: 1250,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:law',
    objectType: 'MPResearchField',
    name: 'Law',
    priority: 1300,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    _id: 'MPResearchField:literature',
    objectType: 'MPResearchField',
    name: 'Literature',
    priority: 1350,
    bundled: true,
    createdAt: 0,
    updatedAt: 0,
  },
]
